### ISSUE TITLE
建议一波?!

### ISSUE THREAD

**Issue by YeFei572** [quec1994/spring-boot-example#1]
<font size=3>
我是搜redis缓存的代码的时候搜到了作者的proj, 个人正在干着和作者一样的工作. 原因跟作者一个样儿, 不过时间断断续续的比作者长一点. 以下说些建议供作者参考一下:

- ### 项目架构
我认为现在作者集成的东西已经比较多了,  但是当前流行的技术还有很多(后面会提到), 随着集成的越来越多项目的架构就必须越来越清晰, 否则代码臃肿, 耦合性太强. 可读性太差, 所以建议作者采用分布式,单独开一个配置模块,相信无论从代码可读性或是耦合性出发都会好很多
- ### 技术方面
    - 鉴权方面: 一个项目必须有鉴权系统, 否则所有接口都是敞开性肯定不合适, 建议整合`jwt+springsecurity` 或是`shiro` 实现鉴权系统的完整性
    - redis: 本来是搜redis实现耦合性不强的缓存才搜到作者的项目, 但是好像项目中没有提到redis的缓存使用, 只有简单CURD, 很遗憾哈, 无论缓存, 中控服务器等使用redis都是非常适合的.
    - rabbitmq: 消息队列作者已经整合了, 而且比较详细, 但是我感觉作者配置写的好紧凑, 看起来有些费力, 我是配置和绑定配置分开了写, 清晰明了, 另外建议作者在消费者使用线程等待5s中看看是不是多线程的,我感觉你的配置有点问题, 只是没有细看. 有可能是我看错了.
    - swagger: 我自己也集成了, 但是我感觉这个东西看起来真恶心, 污染代码, 文档还不能写的很清楚,所以我后面准备剔除了
    - websocket: 及时通讯, 现在很多网站开发响应式的效果, 这个技术占了很大功劳  
    - webservice: 第三方对接经常使用的,没什么多说的
    - 定时任务quartz: 虽说springboot自带定时任务, 但是一般复杂定时任务都是通过数据库动态配置
- ### 异常方面
建议做成自定义异常类, RESTFUL风格的接口这种异常定义还是很有必要.
暂时想到这么多,如果哪儿说的不对还请包涵. 以上建议只供参考,别无他意,喜欢探讨,欢迎骚扰!

</font>

**Comment by quec1994** [comment]
谢谢，意见很好

- redis的话，是有个简单的存取的，再controller包中

- rabbitmq的话，我项目中也没加什么配置

- 其它的，建议很好，我后期会去学习后加上去的

**Comment by quec1994** [comment]
自定义异常类也是有的
